### ISSUE TITLE
faet:make the theme avaible for hyprdots with theme patcher.

### ISSUE THREAD

**Issue by m1guer** [cafreo/hyprland-intergalactic#1]
Hyprdtos supports theming:https://github.com/prasanthrangan/hyprdots/wiki/Theming
and i wanna know if have a little chance to you port ur theme tho Hyprdots.

**Comment by cafreo** [comment]
that doesn't look too hard to do. but it will certainly take a bit of time. i will add it to my to do list and look further into it later

**Comment by m1guer** [comment]
thx ;P
